### ISSUE TITLE
being disconnected on mineplex continuously

### ISSUE THREAD

**Issue by veloute** [8bitFra/Vanilla-Spoof#2]

**Comment by 8bitFra** [comment]
Sorry for the delay in replying, however I am aware of this but I am not able to solve this problem as this is not my code, I have only exported this module from the Wurst client. The only thing you can hope for is that in the event of an update this thing will resolve itself.

**Comment by veloute** [comment]
i've seen the wurst module has been updated a few times since the last repo update, would it be possible to pull in those changes?

**Comment by 8bitFra** [comment]
I cannot guarantee that I will be able to do this in a reasonable period due to lack of time.  However it is something that I have on the list of things to do.

**Comment by veloute** [comment]
no worries mate

**Comment by 8bitFra** [comment]
I updated the mod to minecraft 1.19.2 with the changes I found on the wurst module, can you check if you still have the problem?

**Comment by veloute** [comment]
after a quick test, it looks to be working! I'll keep using it for now to see if anything changes.

**Comment by veloute** [comment]
works, cheers :)
